language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - composer self-update --1

install:
    - composer install
    - composer global require maglnet/composer-require-checker && $HOME/.composer/vendor/bin/composer-require-checker

script: vendor/bin/phpspec run
