language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

env:
  - COMPOSER_REQUIRE_CHECKER_VERSION=2.1.0
  - COMPOSER_REQUIRE_CHECKER_VERSION=3.1.0

matrix:
  exclude:
    - php: '7.2'
      env: COMPOSER_REQUIRE_CHECKER_VERSION=3.1.0
    - php: '7.3'
      env: COMPOSER_REQUIRE_CHECKER_VERSION=3.1.0
    - php: '7.4'
      env: COMPOSER_REQUIRE_CHECKER_VERSION=3.1.0
    - php: '8.0'
      env: COMPOSER_REQUIRE_CHECKER_VERSION=2.1.0
cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - if [ $COMPOSER_REQUIRE_CHECKER_VERSION = "2.1.0" ]; then
        composer self-update --1;
      else
        composer self-update;
      fi

install:
    - composer install
    - composer global require maglnet/composer-require-checker:^${COMPOSER_REQUIRE_CHECKER_VERSION} && `composer config --global home`/vendor/bin/composer-require-checker

script: vendor/bin/phpspec run
